name: /home/jovyan/.mlspace/envs/synt-pipe
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - annotated-types=0.7.0
  - anyio=4.12.1
  - backports.zstd=1.3.0
  - boto3=1.42.33
  - botocore=1.42.34
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - certifi=2026.1.4
  - charset-normalizer=3.4.4
  - colorama=0.4.6
  - distro=1.9.0
  - exceptiongroup=1.3.1
  - h11=0.16.0
  - h2=4.3.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - idna=3.11
  - jiter=0.12.0
  - lcms2=2.18
  - ld_impl_linux-64=2.45
  - lerc=4.0.0
  - libblas=3.11.0
  - libcblas=3.11.0
  - libdeflate=1.25
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libopenblas=0.3.30
  - libpng=1.6.54
  - libsqlite=3.51.1
  - libstdcxx=15.2.0
  - libtiff=4.7.1
  - libuuid=2.41.3
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - numpy=2.2.6
  - openai=2.15.0
  - openjpeg=2.5.4
  - openssl=3.6.1
  - pandas=2.3.3
  - pillow=12.1.0
  - pip=25.3
  - pthread-stubs=0.4
  - pydantic=2.12.5
  - pydantic-core=2.41.5
  - pysocks=1.7.1
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.3
  - python_abi=3.10
  - pytz=2025.2
  - readline=8.3
  - reportlab=4.4.3
  - s3transfer=0.16.0
  - setuptools=80.9.0
  - six=1.17.0
  - sniffio=1.3.1
  - tk=8.6.13
  - tqdm=4.67.1
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025c
  - urllib3=2.6.3
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - zlib-ng=2.3.2
  - zstd=1.5.7
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - albucore==0.0.24
      - albumentations==2.0.8
      - annotated-doc==0.0.4
      - anthropic==0.71.0
      - apache-tvm-ffi==0.1.8.post2
      - astor==0.8.1
      - async-timeout==5.0.1
      - attrs==25.4.0
      - awscli==1.44.24
      - blake3==1.0.8
      - bracex==2.6
      - cachetools==6.2.4
      - cbor2==5.8.0
      - cffi==2.0.0
      - click==8.3.1
      - cloudpickle==3.1.2
      - compressed-tensors==0.12.2
      - cryptography==46.0.3
      - cuda-bindings==13.1.1
      - cuda-pathfinder==1.3.3
      - cuda-python==13.1.1
      - cupy-cuda12x==13.6.0
      - depyf==0.20.0
      - dill==0.4.0
      - diskcache==5.6.3
      - dnspython==2.8.0
      - dockerfile-parse==2.0.1
      - docstring-parser==0.17.0
      - docutils==0.19
      - e2b==2.10.1
      - e2b-code-interpreter==2.4.1
      - einops==0.8.1
      - email-validator==2.3.0
      - fastapi==0.128.0
      - fastapi-cli==0.0.20
      - fastapi-cloud-cli==0.10.1
      - fastar==0.8.0
      - fastrlock==0.8.3
      - filelock==3.20.3
      - flashinfer-python==0.5.3
      - frozenlist==1.8.0
      - fsspec==2026.1.0
      - gguf==0.17.1
      - hf-xet==1.2.0
      - httptools==0.7.1
      - httpx-sse==0.4.3
      - huggingface-hub==0.36.0
      - ijson==3.4.0.post0
      - interegular==0.3.3
      - jinja2==3.1.6
      - jmespath==1.0.1
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - lark==1.2.2
      - llguidance==1.3.0
      - llvmlite==0.44.0
      - lm-format-enforcer==0.11.3
      - loguru==0.7.3
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mcp==1.25.0
      - mdurl==0.1.2
      - mistral-common==1.8.8
      - model-hosting-container-standards==0.1.13
      - mpmath==1.3.0
      - msgpack==1.1.2
      - msgspec==0.20.0
      - multidict==6.7.0
      - networkx==3.4.2
      - ninja==1.13.0
      - numba==0.61.2
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cudnn-frontend==1.17.0
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-cutlass-dsl==4.3.5
      - nvidia-ml-py==13.590.44
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - openai-harmony==0.0.8
      - opencv-python-headless==4.12.0.88
      - outlines-core==0.2.11
      - packaging==25.0
      - partial-json-parser==0.2.1.1.post7
      - prometheus-client==0.24.1
      - prometheus-fastapi-instrumentator==7.1.0
      - propcache==0.4.1
      - protobuf==6.33.4
      - psutil==7.2.1
      - py-cpuinfo==9.0.0
      - pyasn1==0.6.2
      - pybase64==1.4.3
      - pycountry==24.6.1
      - pycparser==2.23
      - pydantic-extra-types==2.11.0
      - pydantic-settings==2.12.0
      - pygments==2.19.2
      - pyjwt==2.10.1
      - pymupdf==1.26.7
      - python-dotenv==1.2.1
      - python-json-logger==4.0.0
      - python-multipart==0.0.21
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - ray==2.53.0
      - referencing==0.37.0
      - regex==2026.1.14
      - requests==2.32.5
      - rich==14.2.0
      - rich-toolkit==0.17.1
      - rignore==0.7.6
      - rpds-py==0.30.0
      - rsa==4.7.2
      - safetensors==0.7.0
      - scipy==1.15.3
      - sentencepiece==0.2.1
      - sentry-sdk==2.49.0
      - setproctitle==1.3.7
      - shellingham==1.5.4
      - simsimd==6.5.12
      - sse-starlette==3.1.2
      - starlette==0.50.0
      - stringzilla==4.6.0
      - supervisor==4.3.0
      - sympy==1.14.0
      - tabulate==0.9.0
      - tiktoken==0.12.0
      - tokenizers==0.22.2
      - tomli==2.4.0
      - torch==2.9.0
      - torchaudio==2.9.0
      - torchvision==0.24.0
      - transformers==4.57.5
      - triton==3.5.0
      - typer==0.21.1
      - uvicorn==0.40.0
      - uvloop==0.22.1
      - vllm==0.13.0
      - watchfiles==1.1.1
      - wcmatch==10.1
      - websockets==16.0
      - xgrammar==0.1.27
      - yarl==1.22.0
prefix: /home/jovyan/.mlspace/envs/synt-pipe
